services:
  - type: web
    name: joe-datastrike
    env: node
    buildCommand: npm run build
    startCommand: npm start
    envVars:
      - key: MONGODB_URI
        sync: false
      - key: NODE_ENV
        value: production
